### ISSUE TITLE
The blog web had been broken: comments not work anymore

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#218]
I believe the problem was introduced from #205 by @824zzy 

```ts
Uncaught ReferenceError: MathJax is not defined
    at MathJaxLocal.js:1
```

In order to make the system more robust, I'd like to suggest the following two rules in the future:

1. Split the PR into minimum units for each modification, by creating different branches for them.
1. Test the blog system from localhost by run `make serve` and make sure everything is ok if you modify any system files.

**Comment by 824zzy** [comment]
Run `make serve` did not give me any warnings or errors. I will fix this error soon.

**Comment by huan** [comment]
Thanks!

The `make serve` did not help because this issue is a javescript error, which could only be found in the browser with the specified feature.

And that's the reason why I said that we should be very careful when modify the system theme files.

**Comment by 824zzy** [comment]
![image](https://user-images.githubusercontent.com/13566583/61926802-bf455480-afa4-11e9-94f9-a5c3b8113af5.png)

Local test does not show comments. So it is very hard to debug. Let me guess where is the bug. LOL

**Comment by huan** [comment]
Yeah, that's why we have to be very careful.

**Comment by huan** [comment]
![image](https://user-images.githubusercontent.com/1361891/61936840-1b69a200-afc0-11e9-89e2-aa078d48e56e.png)

It seems that the pagination had also been in inflected.

**Comment by huan** [comment]
The pagination and comment are still but functional...

**Comment by huan** [comment]
Thanks, @824zzy, this issue had been resolved!
