### ISSUE TITLE
[bug] show error on the phone

### ISSUE THREAD

**Issue by VDeamoV** [BUPT/ai-ml.club#222]
It seems we the layout of the blog is wrong on the phone(iphong7). The menu on the top didn't fit the screen correctly so you can not touch the tag, such as `people` on it.

**Comment by huan** [comment]
Maybe related to #218

**Comment by VDeamoV** [comment]
I think this is a bug of layout, specifically on phones(PC is ok), however #218 is some disfunction for the comment part. Maybe they are different two bugs. I wonder whether the theme itself can fit the phone screen.

**Comment by huan** [comment]
Of course it can.

You can visit blog.chatie.io for example.

**Comment by VDeamoV** [comment]
Get it, it seems we miss a "three little line" on the right left corner.

**Comment by VDeamoV** [comment]
I found it fix now～
