### ISSUE TITLE
申请之前顺延的oral参加8/11的AMC

### ISSUE THREAD

**Issue by initc** [BUPT/ai-ml.club#250]
之前的PR链接 https://github.com/BUPT/ai-ml.club/pull/207

**Comment by huan** [comment]
我本次沙龙活动申请挂靠胜杰同学，谢谢～

**Comment by qhduan** [comment]
> 我本次沙龙活动申请挂靠胜杰同学，谢谢～

这么说就不用讲的意思了吗？

**Comment by CyFeng16** [comment]
Got it.
