### ISSUE TITLE
Bug: Members List Page is empty now

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#269]
<https://ai-ml.club/people/>

The page did not display any members on the list, I believe there's a PR introduce a bug for it.

It had been broken and need to be fixed.

![image](https://user-images.githubusercontent.com/1361891/63483598-8cbd4780-c4cf-11e9-94af-715e4fc2f16a.png)

**Comment by huan** [comment]
Confirmed that this bug was introduced by @cgpeter96 from 

https://github.com/BUPT/ai-ml.club/commit/52badbe8dfa592147d400a30ff4795a246adb339

@cgpeter96 Could you please fix this problem and make the member list page work again? Thanks.

**Comment by huan** [comment]
@VDeamoV You had approved the PR #260

The approving process is a requirement to make sure all the changes are OK, however, please have a look back to <https://github.com/BUPT/ai-ml.club/pull/260/files> and see what you had approved.

It had at least:

1. broken 2 files with the conflictions without resolving them before the merge
1. introduce too many unrelated changes.

Please help @cgpeter96 to fix those problems, thanks!

**Comment by huan** [comment]
I believe we should revert the commit from <https://github.com/BUPT/ai-ml.club/commit/1cee57eced89eccc9c58fb8eea173c3effc5a4e7> first, then make another PR to publish the blog again.

**Comment by VDeamoV** [comment]
@cgpeter96 file exist ‘HEAD’ ‘>>>>>’ remaining in the author.yml after fix conflict, I think this cause the issue. 

@huan we will check it out, I think we can just recover author.yml to fix the error.

**Comment by VDeamoV** [comment]
Problem solved~

**Comment by huan** [comment]
@VDeamoV Great done!
