### ISSUE TITLE
We lost our website footers

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#271]
Current it is:

![image](https://user-images.githubusercontent.com/1361891/63491184-20e7d880-c4e9-11e9-9bcc-3c5ca0bded44.png)

What it should be:

![image](https://user-images.githubusercontent.com/1361891/63491199-29401380-c4e9-11e9-950a-f409d9359429.png)

We need to find out which part was wrong (and introduced from which PR) so that we could be able to fix it.

**Comment by VDeamoV** [comment]
before this [issue](https://github.com/BUPT/ai-ml.club/issues/262) timestamp，everything is fine

**Comment by huan** [comment]
Thank you @qhduan for fixing this problem!

We now have our footer again, cheers!
