### ISSUE TITLE
The teaser image is not set right for S3E1

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#282]
@CyFeng16 

The teaser image in https://ai-ml.club/events/seminar-meeting-minutes-3-1/ is from S2E20, which is not right. It should be updated to the photo from S3E1.

See:

![image](https://user-images.githubusercontent.com/1361891/63832131-baf4c880-c9a2-11e9-9583-9eaacd9aa10a.png)

**Comment by CyFeng16** [comment]
I'll check it out later this day.

**Comment by CyFeng16** [comment]
@huan #283 PTAL & THX

**Comment by huan** [comment]
Thanks for the fixing!

**Comment by CyFeng16** [comment]
you are welcome.
