### ISSUE TITLE
20190622.pdf of S03E04 does not display properly

### ISSUE THREAD

**Issue by CyFeng16** [BUPT/ai-ml.club#299]
@newip, please check it, thanks.

**Comment by newip** [comment]
代码看不出问题，点击下载可以看。但直接窗口中是看不来。有什么可以尝试的方向？

**Comment by CyFeng16** [comment]
@newip You can try to regenerate the pdf file using Adobe Acrobat DC and then try it out. I suspect the reason ViewerJS did not display correctly is the no standard content in the pdf file.

**Comment by newip** [comment]
The download button is ok. But the content displays not ok. Right now, the 1st pdf viewer does not work either.

**Comment by VDeamoV** [comment]
The URL link for the pdf causes the error, I fix it by reference to the seminar-3-1 file. 

- [x] Checked PDF display ok now
