### ISSUE TITLE
add member to bupt and then AMC chair

### ISSUE THREAD

**Issue by newip** [BUPT/ai-ml.club#300]
Github ID gaojiuy is not a member of BUPT. Because of it, the account cann't be added into AMC chair group. @huan

**Comment by huan** [comment]
Inivited.

> You've invited gaojiuy to Beijing University of Posts and Telecom! They'll be receiving an email shortly. They can also visit https://github.com/BUPT to accept the invitation.

**Comment by newip** [comment]
@gaojiuy  Please ensure you have had accepted the invitation. The ID still not listed in the repo org members. 

![image](https://user-images.githubusercontent.com/1592542/64512328-ba502080-d318-11e9-9d7e-6eccc93c98cc.png)

![image](https://user-images.githubusercontent.com/1592542/64512341-c3d98880-d318-11e9-9ec9-20e56d773a0e.png)

**Comment by newip** [comment]
Done with both Jiuyi part and my part. The chair right granted. Hence close it.

**Comment by huan** [comment]
Contratulations! :+1:
