### ISSUE TITLE
please delete temp(useless) patches after PR, thanks.

### ISSUE THREAD

**Issue by CyFeng16** [BUPT/ai-ml.club#308]

**Comment by CyFeng16** [comment]
@VDeamoV @newip :-)

**Comment by VDeamoV** [comment]
Ok, fixed~ :)

**Comment by huan** [comment]
We also need to merge #243 ASAP because it had been there for too long times.

@TuringLee

**Comment by newip** [comment]
@CyFeng16      I have done my part. Thanks for the issue. Close if it was satisfied.
