### ISSUE TITLE
S03E05 活动纪要 问题反馈

### ISSUE THREAD

**Issue by CyFeng16** [BUPT/ai-ml.club#321]
`詹泽诚`图像显示错误
`张璐` `高久怡` `授蛋` `合照` `AF` 图像比例失调
`李卓桓`PDF无法正常显示和下载
麻烦当期轮值主席@gaojiuy && 轮值副主席@ArronHZG 检查并修改
辛苦辛苦 :tada:

**Comment by huan** [comment]
Thank you @CyFeng16 for pointing those problems out!

It is very important that in AMC everyone should keep our eyes on the outcome after merging a Pull Request so that we can keep our quality high, and bug free!

**Comment by ArronHZG** [comment]
Yes,it's important to ensure high quality, so I will re-upload the image tomorrow and fix the PDF display.

**Comment by VDeamoV** [comment]
在新的 pr merge 之后， 图像比例失调情况依旧存在。@ArronHZG

**Comment by CyFeng16** [comment]
在新的 pr merge 之后， 存在PDF不显示的问题。@ArronHZG

**Comment by CyFeng16** [comment]
The problem had been solved so the issue closed.
