### ISSUE TITLE
All PDF files get 404 error

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#358]
After we moved to surge.sh.

Need to be fixed.

**Comment by CyFeng16** [comment]
辛辛苦苦修补匠 多灾多难AMC :trollface:

**Comment by huan** [comment]
This is life~

**Comment by huan** [comment]
Related to https://github.com/sintaxi/surge/issues/302

**Comment by huan** [comment]
The pdf file download had been fixed after I bind the credit card to my account.

The Surge.sh website said that only the paid plan will get the PDF download support, however, as the issue 302 said: after the user bind the credit, the pdf download function will be enabled, without need to change to a paid plan.

Cheers!

BTW: another static HTML hosting service is <https://netlify.com>. It works great with PDF files, but it does not fetch the viewer-js/* files from the Git LFS, wired.

**Comment by fuyunfuyun666** [comment]
可以看见了

**Comment by fuyunfuyun666** [comment]
前面的好像看不见

**Comment by huan** [comment]
@fuyunfuyun666 “前面的”的具体地址是什么？

**Comment by VDeamoV** [comment]
this [blog](https://github.com/BUPT/ai-ml.club/issues/358) now seems okay.

**Comment by fuyunfuyun666** [comment]
> @fuyunfuyun666 “前面的”的具体地址是什么？
https://ai-ml.club/events/seminar-meeting-minutes-3-5/

**Comment by CyFeng16** [comment]
Confirm that S3E5's PDFs cannot be viewed.

**Comment by huan** [comment]
@fuyunfuyun666 @CyFeng16 The reason of the PDFs in S3E5 can not be displayed is not related to this deploy issue.

It's because the URL of the PDF is not right. @gaojiuy had made the same mistakes as the @ArronHZG before: use the Github file url(wrong) instead of it's AMC URL(right).

From <https://github.com/BUPT/ai-ml.club/blob/master/docs/_posts/2019-09-08-seminar-meeting-minutes-3-5.md>:

```markdown
高久怡 @gaojiuy

分享了论文Axiomatic Attribution for Deep Networkss and Saliency Maps

![高久怡]({{ '/assets/2019/seminar-3-5/seminar-3-5-talk-gaojiuy.jpg'| relative_url }})

<iframe src='{{ '/assets/js/viewer-js/#https://github.com/BUPT/ai-ml.club/blob/master/docs/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf' | relative_url }}' width='560' height='315' allowfullscreen webkitallowfullscreen frameborder="0" style=" position: absolute; top:0; left:0; width:100%; height:100%; " ></iframe>
```

It should be fixed as I demonstrated from the belowing DIFF.

```diff
- /assets/js/viewer-js/#https://github.com/BUPT/ai-ml.club/blob/master/docs/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf
+ /assets/js/viewer-js/#/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf'
```
Is there anyone who wants to help @gaojiuy to send a PR to fix it?

**Comment by huan** [comment]
Close this issue because the deploy problem had been fixed.
