### ISSUE TITLE
S3E5 meeting minutes have problem to show the PDF files.

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#364]
Separated from #358 

@fuyunfuyun666 @CyFeng16 The reason of the PDFs in S3E5 can not be displayed is not related to this deploy issue.

It's because the URL of the PDF is not right. @gaojiuy had made the same mistakes as the @ArronHZG before: use the Github file url(wrong) instead of it's AMC URL(right).

From <https://github.com/BUPT/ai-ml.club/blob/master/docs/_posts/2019-09-08-seminar-meeting-minutes-3-5.md>:

```markdown
高久怡 @gaojiuy

分享了论文Axiomatic Attribution for Deep Networks and Saliency Maps

![高久怡]({{ '/assets/2019/seminar-3-5/seminar-3-5-talk-gaojiuy.jpg'| relative_url }})

<iframe src='{{ '/assets/js/viewer-js/#https://github.com/BUPT/ai-ml.club/blob/master/docs/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf' | relative_url }}' width='560' height='315' allowfullscreen webkitallowfullscreen frameborder="0" style=" position: absolute; top:0; left:0; width:100%; height:100%; " ></iframe>
```

It should be fixed as I demonstrated from the blowing DIFF.

```diff
- /assets/js/viewer-js/#https://github.com/BUPT/ai-ml.club/blob/master/docs/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf
+ /assets/js/viewer-js/#/assets/2019/seminar-3-5/seminar-3-5-integrad.pdf'
```
Is there anyone who wants to help @gaojiuy to send a PR to fix it?

**Comment by Duan-JM** [comment]
S3E5 meetings' pdf are good to go now, thanks for @gaojiuy effort!

**Comment by huan** [comment]
Great. 

I'd like to suggest that we should reference the ISSUE in our PR so that we can connect everything together. (which I had just modified the PR of @gaojiuy
