### ISSUE TITLE
S3E13 meeting minutes photos ratio is not right

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#425]
https://ai-ml.club/events/seminar-meeting-minutes-3-13/

这个纪要里面的图片比例失调，昨天和张璐碰过之后，应该是 @陈光 的 Python Script 在 fit images 的时候，没有严格按照原始图像的 ratio 进行缩放的缘故。请二位这周协调一下发一个 fix 哈。

**Comment by cgpeter96** [comment]
代码没问题， 应该是使用
```
python fit_image.py --images xxxx --width 1920 
# 该方式是修改宽度，高度按照比例调整

python fit_image.py --images xxxx --width 1920  --widht 1080
# 该方式是默认使用者已经知道了，图片应该调整为如上分辨率
```

**Comment by huan** [comment]
@cgpeter96 great to know that the code is ok!

Could you please add more documentation so that we can make our user use the script properly?

Thank you very much!
