### ISSUE TITLE
关于“长期睦邻友好合作组织之间的流动会员席位制度”的意见收集稿

### ISSUE THREAD

**Issue by CyFeng16** [BUPT/ai-ml.club#429]
# 关于“长期睦邻友好合作组织间的流动会员席位制度”的意见收集稿

## 当前论文分享会[会员准入机制](https://ai-ml.club/manuals)摘录如下：

1. 会员要求：
   1. 对AI/ML研究方向有激情
   2. 有强烈论文学习和研讨意愿
2. 新人准入机制：
   1. 通过一位 AMC 俱乐部的正式会员推荐
   2. 新人第一次可以允许不提交Pull Request参会
   3. 如果第二次还想参加活动，则需要按会员要求(分享论文)必须提交 PR 后，方可作为见习会员加
3. 会员挂靠机制：
   1. 依据
      1. https://github.com/BUPT/ai-ml.club/issues/61
      2. https://github.com/BUPT/ai-ml.club/issues/62
   2. 描述：参会要求适当放宽，允许会员不分享论文参会，但是每次需挂靠一个分享论文的会员，每个会员一次会议只能被一个不分享论文的同学挂靠。

---

## 拟制定**流动会员席位制度**:

1. 目的：

   1. 加强其他组织中的会员流动(流入)
   2. 加深组织之间的合作关系 建立沟通渠道
   3. 与不同质组织之间互通有无 相互扩大影响力

2. 实施方法(拟定)：

   1. ***坚持*** 和完善AMC基本准入制度[**毫不动摇**]

   2. **完善** 挂靠机制：

      1. **挂靠席位**

         情景假设：当前报名参加当期AMC的演讲者(oral/poster)4人，AMC内部正式会员报名挂靠2人，则剩余挂靠席位2人。

      2. **流动席位**

         流动席位是对挂靠机制下产生的挂靠席位的有力补充，在保持最优参与人员数量限制的同时，将剩余挂靠席位有效分配给长期睦邻友好合作组织成员。

      3. **流动席位制度**(拟定)

         1. 为定义为AMC“长期睦邻友好合作组织”的组织提供不超过2席位的流动席位**数量**

         2. 当期AMC流动席位**总量**由分享会开启前48小时时剩余挂靠席位决定，即：

            来自“长期睦邻友好合作组织”的报名者应在周五晚7点后参与挂靠，挂靠推荐填写为挂靠组织名称

            应用流动席位报名在当期AMC周五晚7点前无效，周五晚7点后和AMC正式会员拥有等效挂靠报名优先级，遵循先到先得原则

         3. 采用“长期睦邻友好合作组织”的流动席位参会的人员**不受新人第二次参加活动的限制**，但鼓励之后积极参与AMC称为正式会员

---

### 欢迎诸位AMC正式会员对本**意见稿**广开思路，献计出力

<p align="right">C.Feng 2019年11月21日</p>

**Comment by newip** [comment]
还是有些复杂了，是在“可用挂靠名额中“提供两个不限制来访次数的“流动席位名额”，是这个意思么？就是没有可用挂靠名额了就没有这个席位。但当可挂靠席位较多时，提供给流动席位的名额可以大于2个，但不能超过可用数，是么？

**Comment by CyFeng16** [comment]
> 还是有些复杂了，是在“可用挂靠名额中“提供两个不限制来访次数的“流动席位名额”，是这个意思么？就是没有可用挂靠名额了就没有这个席位。但当可挂靠席位较多时，提供给流动席位的名额可以大于2个，但不能超过可用数，是么？

可挂靠的剩余席位中提供为流动席位，每次为每个组织最多提供2个流动席位(防止单一组织抢占过多)
如果本次没有剩余可挂靠席位，则本次无可提供的流动席位。

**Comment by Duan-JM** [comment]
对于制度本身能吸引更多的新人多次参加来增加AMC的活跃程度这点，非常赞同，也非常感谢师兄能以一种条理非常清晰的形式展现出来。

对其中有一个问题是“长期睦邻友好合作组织”的定义是怎么确定的呢，这个可能是一个新引入的概念，不知道是不是可以加一个判定的标准或者一个审批的流程呢。如 “ 在 AMC 主要活跃主席一致投票认可的合作组织” 或者 “对AMC提供了XXX赞助/帮助的合作组织”。

**Comment by CyFeng16** [comment]
> 对于制度本身能吸引更多的新人多次参加来增加AMC的活跃程度这点，非常赞同，也非常感谢师兄能以一种条理非常清晰的形式展现出来。
> 
> 对其中有一个问题是“长期睦邻友好合作组织”的定义是怎么确定的呢，这个可能是一个新引入的概念，不知道是不是可以加一个判定的标准或者一个审批的流程呢。如 “ 在 AMC 主要活跃主席一致投票认可的合作组织” 或者 “对AMC提供了XXX赞助/帮助的合作组织”。

Good idea! 
嘉铭可不可以根据自己的理解粗略给出个答案，我更新在上面

**Comment by Duan-JM** [comment]
> Good idea!
> 嘉铭可不可以根据自己的理解粗略给出个答案，我更新在上面

目前只是发现了这个可能的潜在小问题，还没有想出能让我自己比较满意的答案，同时这个流动席位的设定可能还对 EC 有一定的助力。不知道 桓哥 新哥 @newip @huan  怎么看这个问题呀。

**Comment by newip** [comment]
长期睦邻友好合作组织确实需要一个精简的名称和定义。名称可否改为：AMC Corp Member，AMC组织会员。
是会员了就可以有责权利，就需要Manual，似乎又复杂了些。但感觉上还是需要，可以和EC组的行动计划挂钩了，因为我们一直在定义赞助会员的权益，但实际上还没有给企业会员一个身份。
责任：
1. 引入潜在合格会员以及新成员，且会员引入成功率高于50%
2. 对AMC提供发展支持（包括不限于：资金、设备、宣传、代码、文档、场地等）
权力：
1. 享有流动席位
2. 办理专场活动
利益：
1. 优先获取MM项目最新进展
2. 经双方同意，在AMC主要入口提供会员Logo展示
3. 在MM系统中展示Logo

**Comment by CyFeng16** [comment]
> 长期睦邻友好合作组织确实需要一个精简的名称和定义。名称可否改为：AMC Corp Member，AMC组织会员。
> 是会员了就可以有责权利，就需要Manual，似乎又复杂了些。但感觉上还是需要，可以和EC组的行动计划挂钩了，因为我们一直在定义赞助会员的权益，但实际上还没有给企业会员一个身份。
> 责任：
> 
> 1. 引入潜在合格会员以及新成员，且会员引入成功率高于50%
> 2. 对AMC提供发展支持（包括不限于：资金、设备、宣传、代码、文档、场地等）
>    权力：
> 3. 享有流动席位
> 4. 办理专场活动
>    利益：
> 5. 优先获取MM项目最新进展
> 6. 经双方同意，在AMC主要入口提供会员Logo展示
> 7. 在MM系统中展示Logo
> 
> @huan @secortot @琳玉

@AlaskaaWong @newip 
会员转化率是不是有些……

**Comment by CyFeng16** [comment]
相关讨论已同步更新到[AMC OKR Meeting Notes](https://docs.google.com/document/d/1OWBVUvM3lQrwOURdhEGgvR4xaVCc5ZG1F4D7MR3jKFQ/edit?usp=sharing)
总结两点如下：
- 定义合作组织
- 定义流动席位

如果可以得到一个简明易懂且具备一定长期可行性的方案，相信无论是对合作组织还是对我们AMC的未来发展都具有意义。

稍后会根据大家如上的建议总结一下，在11月24日OKR Meeting上讨论决议，欢迎参加线下讨论。[报名](https://docs.google.com/document/d/1OWBVUvM3lQrwOURdhEGgvR4xaVCc5ZG1F4D7MR3jKFQ/edit?usp=sharing)

**Comment by CyFeng16** [comment]
进入为期两个月的试用期
Closed.
