### ISSUE TITLE
Blog post file name confliction

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#70]
See: https://github.com/BUPT/awesome-chatbot/pull/67#issuecomment-456417716

seminar-meeting-minutes-22.md 你的文件名应该是 -23 结尾。

现在的名称和老的文件名冲突了，导致博客显示相关链接不正常了（两个都是一样的url地址），需要fix一下。

@cgpeter96

**Comment by cgpeter96** [comment]
好的
