### ISSUE TITLE
我们文章中所有图片，请务必上传到我们自己的 repo 指定目录下引用

### ISSUE THREAD

**Issue by huan** [BUPT/ai-ml.club#94]
最后一次沙龙日志中，图片显示有问题：
https://github.com/BUPT/awesome-chatbot/blob/master/docs/_posts/2019-04-21-seminar-meeting-minutes-2-8.md

@YapheeetS 用了外部图片上传服务，请改为存放在我们自己的 repo 指定目录下面，具体路径请参考之前的文章。

@824zzy 在 Merge PR 之前，请一定注意检查相关文件存放是否标准。

因为如果我们用了外部的图片服务，未来一定图片就无法显示了。所以为了保存好我们珍贵的照片，一定要把图片都存放在咱们自己的  repo 中。

相关问题代码如下：

```md
## 沙龙内容

1. 朱正源 @824zzy 分享 [初代神经图灵机原理与代码](https://bupt.github.io/conversational-ai-club/#/papers/neural-turing-machines-2014)

 ![](http://ww1.sinaimg.cn/large/b3beb1ffgy1g2am71n91lj23402c0npo.jpg)
```

另外，日志中也没有记录活动相关的决议，比如下次的主席和副主席人选，等。请在未来会议纪要中继续提升。

**Comment by 824zzy** [comment]
I have noticed @YapheeetS to transform external image URLs to local URLs.

And I will check out the PR in details in future~ 😀

PS: the vice-chairman will be the chairman next time. But it ought to append vice-vice-chairman in the `Conclusion` section. 😢

**Comment by 824zzy** [comment]
@YapheeetS 这次的纪要都发了，回家可别忘了改啊

**Comment by huan** [comment]
@YapheeetS Please close this issue after you fixed it. Thanks! :)

**Comment by YapheeetS** [comment]
@huan The problem was fixed, but this issue must be closed by you.

**Comment by YapheeetS** [comment]
@huan I can not close the issue, because it was opened by you ?

**Comment by huan** [comment]
@YapheeetS Oh, yes, you are right.

I'll close it for you, thank you very much!
